version: "3.6"

services:
  web:
    image: 4architmehta/sem-class:${SEM_IMG_TAG}
    volumes:
      - "./prediction:/usr/app/prediction"
      - "/etc/letsencrypt:/etc/letsencrypt"
    ports:
      - "443:8000"