name: Build and Deploy to Google Compute Engine

on:
  push:
    branches:
      - "main"

env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}
  GCE_INSTANCE: personal-projs
  GCE_INSTANCE_ZONE: us-east4-c

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Auth Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Authentication via credentials json
      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      # Setup gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker

      # Build the Docker image
      - name: Build
        run: |-
          docker build --tag "4architmehta/sem-class:$GITHUB_SHA" ./backend/

      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |-
          docker push "4architmehta/sem-class:$GITHUB_SHA"

      - name: SSH & Deploy
        uses: appleboy/ssh-action@master
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_PASSWORD }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            sudo docker stop sem-cls-backend
            sudo docker pull 4architmehta/sem-class:$GITHUB_SHA
            sudo docker run -dp 443:8000 --name sem-cls-backend --mount type=bind,source=/etc/letsencrypt,target=/etc/letsencrypt 4architmehta/sem-class:$GITHUB_SHA
